title: "Jonathan's Data Science Portfolio"
description: "Projects, notebooks, and data science work."
remote_theme: "mistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects
